---
- hosts: media
  gather_facts: True
  become: true
  
  roles:
    - common
    - docker
    - role: media-docker
      become: true
      become_user: "{{ docker_user_name }}"
      tags: media-docker
    